Added Quadcopter Problem to Documentation
plasmo-dev/Plasmo.jl pull request #117
Opened 2024-08-21 20:23 UTC by rishimandyam

Added quadcopter example to the Plasmo documentation.

2024-08-21 21:57 UTC, dlcole3 commented
I updated this PR so that the quadcopter.jl file is removed from the `examples/` folder.

2024-08-22 04:34 UTC, jalving commented on docs/src/tutorials/quadcopter.md
> +### 2. Function Design
I would suggest splitting the model build into multiple functions as opposed to one splitting one function into multiple snippets. At the end, you could call something like `build_quadcopter_model` that assembles the whole optigraph. To make things easier, you could define each function to accept an optigraph as input and do their modifications. So something like:
```julia
graph = OptiGraph()
data = initialize_data(N)
add_variables(graph, data)
add_initial_condition(graph, data)
add_link_constraints(graph, data)
```

2024-08-22 04:35 UTC, jalving requested changes
see comment

2024-08-22 23:57 UTC, jalving approved these changes

2024-08-23 00:04 UTC, merged